### ISSUE TITLE
changer les couleurs et les matières

### ISSUE THREAD

**Issue by berryergo** [jgirardet/mydevoirs#1]
Bonjour,
Ergothérapeute, je m’intéresse à votre logiciel. Les enfants que j'accompagne ont souvent les titres et des couleurs spécifiques demandé par leur enseignent. Pour ne pas les perturber, je souhaiterai modifier les matières et changer la couleur des bandes matières. 
Votre logiciel est vraiment très visuel, et ces modifications en feront un logiciel vraiment aidant pour nos jeunes.
Dans l'attente de vous lire
Félicitation pour votre travail
Laure Berry

**Comment by jgirardet** [comment]
Bonjour,
J'y ai beaucoup réfléchi au départ puis je me suis dit que la personnalisation n'était pas quelque chose d'aisée pour un enfant  et autant la faire une fois pour toute. Je n'avais pas pensé qu'un professionnel souhaiterait le faire :smile: 
Cela implique pas mal de changements tout de même. Une possibilité serait de passer par un fichier de configuration.

Pensez vous qu'il serait possible pour vous de personnaliser  "à la main" comme ceci ?:
```
{
    "Français": {
        "Orthographe": (91, 193, 242),
        "Grammaire": (153, 200, 245),
        "Conjugaison": (34, 174, 241),
        "Vocabulaire": (2, 162, 240),
        "Rédaction": (0, 120, 255),
    },
    "Mathématiques": {
        "Mathématiques": (216, 88, 243),
        "Géométrie": (229, 151, 246)},
    "Histoire-Géo": {
        "Histoire": (227, 254, 0),
        "Géographie": (236, 254, 87)},
    "Sciences": (255, 177, 88),
    "Musqiue-Poésie": {
        "Musique": (142, 108, 252),
        "Poésie": (186, 165, 252)},
    "Anglais": (255, 90, 90),
    "Divers": (89, 253, 89),
}
```
C'est une imbrication de type `clé:valeur` délimité en "niveau" par `{}` . les valeurs sont les couleur au format rgb est peuvent être obtenues ici : https://www.w3schools.com/colors/colors_picker.asp.
Il suffit de modifier les clé/valeurs et ajouter supprimer des lignes.
Ceci est la configuration actuelle, vous pouvez comparer avec le rendu actuel pour vous donner une idée.

**Comment by berryergo** [comment]
Bonjour,Mercipour votre retour.Je vais essayer et je vous tiens au courant.merci pour les enfants.Laure BerryErgotherapeute Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : jgirardet <notifications@github.com> Date : 06/02/2020  08:31  (GMT+01:00) À : jgirardet/mydevoirs <mydevoirs@noreply.github.com> Cc : berryergo <l.berryergo@orange.fr>, Author <author@noreply.github.com> Objet : Re: [jgirardet/mydevoirs] changer les couleurs et les matières (#1) Bonjour,

J'y ai beaucoup réfléchi au départ puis je me suis dit que la personnalisation n'était pas quelque chose d'aisée pour un enfant  et autant la faire une fois pour toute. Je n'avais pas pensé qu'un professionnel souhaiterait le faire 😄

Cela implique pas mal de changements tout de même. Une possibilité serait de passer par un fichier de configuration.

Pensez vous qu'il serait possible pour vous de personnaliser  "à la main" comme ceci ?:

MATIERES_TREE = {

    "Français": {

        "Orthographe": (91, 193, 242),

        "Grammaire": (153, 200, 245),

        "Conjugaison": (34, 174, 241),

        "Vocabulaire": (2, 162, 240),

        "Rédaction": (0, 120, 255),

    },

    "Mathématiques": {

        "Mathématiques": (216, 88, 243),

        "Géométrie": (229, 151, 246)},

    "Histoire-Géo": {

        "Histoire": (227, 254, 0),

        "Géographie": (236, 254, 87)},

    "Sciences": (255, 177, 88),

    "Musqiue-Poésie": {

        "Musique": (142, 108, 252),

        "Poésie": (186, 165, 252)},

    "Anglais": (255, 90, 90),

    "Divers": (89, 253, 89),

}



C'est une imbrication de type clé:valeur délimité en "niveau" par {} . les valeurs sont les couleur au format rgb est peuvent être obtenues ici : https://www.w3schools.com/colors/colors_picker.asp.

Il suffit de modifier les clé/valeurs et ajouter supprimer des lignes.

Ceci est la configuration actuelle, vous pouvez comparer avec le rendu actuel pour vous donner une idée.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jgirardet/mydevoirs/issues/1?email_source=notifications\u0026email_token=AOORXKKAUCMLXRHNSK46QW3RBO4EZA5CNFSM4KPMHERKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK6GXPI#issuecomment-582773693",

"url": "https://github.com/jgirardet/mydevoirs/issues/1?email_source=notifications\u0026email_token=AOORXKKAUCMLXRHNSK46QW3RBO4EZA5CNFSM4KPMHERKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK6GXPI#issuecomment-582773693",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by berryergo** [comment]
Bonjour,
Je ne mis connais vraiment pas beaucoup, mais j'ai réussi à modifier les lignes matières et couleur mais je ne sais pas comment remettre ensuite le fichir en .exe
Si vous pouvez m'indiquer la démarche à suivre.
Merci d'avance pour votre aide
Laure BERRY
 
 
 
 
> Message du 06/02/20 08:31> De : "jgirardet" > A : "jgirardet/mydevoirs" > Copie à : "berryergo" , "Author" > Objet : Re: [jgirardet/mydevoirs] changer les couleurs et les matières (#1)> >
> Bonjour,> J'y ai beaucoup réfléchi au départ puis je me suis dit que la personnalisation n'était pas quelque chose d'aisée pour un enfant et autant la faire une fois pour toute. Je n'avais pas pensé qu'un professionnel souhaiterait le faire 😄> Cela implique pas mal de changements tout de même. Une possibilité serait de passer par un fichier de configuration.
> Pensez vous qu'il serait possible pour vous de personnaliser "à la main" comme ceci ?:
MATIERES_TREE = {

"Français": {

"Orthographe": (91, 193, 242),

"Grammaire": (153, 200, 245),

"Conjugaison": (34, 174, 241),

"Vocabulaire": (2, 162, 240),

"Rédaction": (0, 120, 255),

},

"Mathématiques": {

"Mathématiques": (216, 88, 243),

"Géométrie": (229, 151, 246)},

"Histoire-Géo": {

"Histoire": (227, 254, 0),

"Géographie": (236, 254, 87)},

"Sciences": (255, 177, 88),

"Musqiue-Poésie": {

"Musique": (142, 108, 252),

"Poésie": (186, 165, 252)},

"Anglais": (255, 90, 90),

"Divers": (89, 253, 89),

}


> C'est une imbrication de type clé:valeur délimité en "niveau" par {} . les valeurs sont les couleur au format rgb est peuvent être obtenues ici : https://www.w3schools.com/colors/colors_picker.asp.> Il suffit de modifier les clé/valeurs et ajouter supprimer des lignes.> Ceci est la configuration actuelle, vous pouvez comparer avec le rendu actuel pour vous donner une idée.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/jgirardet/mydevoirs/issues/1?email_source=notifications\u0026email_token=AOORXKKAUCMLXRHNSK46QW3RBO4EZA5CNFSM4KPMHERKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK6GXPI#issuecomment-582773693", "url": "https://github.com/jgirardet/mydevoirs/issues/1?email_source=notifications\u0026email_token=AOORXKKAUCMLXRHNSK46QW3RBO4EZA5CNFSM4KPMHERKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK6GXPI#issuecomment-582773693", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by jgirardet** [comment]
bonjour,
Il me semble que ce que vous m'avez renvoyez correspond à ce qui est existant.
voici un autre model duquel partir.
```json
{
	"Français": {
		"Orthographe": [
			91,
			193,
			242
		],
		"Grammaire": [
			153,
			200,
			245
		],
		"Conjugaison": [
			34,
			174,
			241
		],
		"Vocabulaire": [
			2,
			162,
			240
		],
		"Rédaction": [
			0,
			120,
			255
		]
	},
	"Mathématiques": {
		"Mathématiques": [
			216,
			88,
			243
		],
		"Géométrie": [
			229,
			151,
			246
		]
	},
	"Histoire-Géo": {
		"Histoire": [
			227,
			254,
			0
		],
		"Géographie": [
			236,
			254,
			87
		]
	},
	"Sciences": [
		255,
		177,
		88
	],
	"Musqiue-Poésie": {
		"Musique": [
			142,
			108,
			252
		],
		"Poésie": [
			186,
			165,
			252
		]
	},
	"Anglais": [
		255,
		90,
		90
	],
	"Divers": [
		89,
		253,
		89
	]
}
```

**Comment by Ergolya** [comment]
Bonjour et merci pour ce soft :-) 

Je vous avais contacté il y a quelques temps et vient de découvrir que l'on pouvait poster des "issues"..

Etant ergothérapeute j'ai la même problématique de personnalisation que mes collègues et souhaite pouvoir le faire de manière autonome.

Avant de découvrir ce post j'avais pu faire ceci : 

MATIERES_TREE = {
    "Français": {
        "Orthographe": (91, 193, 242),
        "Grammaire": (153, 200, 245),
        "Conjugaison": (34, 174, 241),
        "Vocabulaire": (2, 162, 240),
        "Rédaction": (0, 120, 255),
    },
    "Mathématiques": {"Mathématiques": (216, 88, 243), "Géométrie": (229, 151, 246)},
    "Histoire-Géo": {"Histoire": (227, 254, 0), "Géographie": (236, 254, 87), "EMC": (255, 215, 0)},
    "Sciences": (50, 205, 50),
    "SVT": (154, 205, 50),
    "Physique-Chimie": (255, 177, 88),
    "Musique-Poésie": {"Musique": (142, 108, 252), "Poésie": (186, 165, 252)},
    "Arts Plastiques": (255, 177, 88),
    "Anglais": (255, 90, 90),
    "Espagnol": (139, 0, 139),
    "Divers": (192, 192, 192),
}

mais, je coince au moment de le remettre en fichier exécutable.

J'aimerais pouvoir le faire moi-même, car l'exemple indiqué ci-dessus ne correspond pas à tous les jeunes que j'accompagne. Je dois pouvoir être libre de modifier les couleurs ou matières.


J'avais pu configurer rainlendar en ajoutant des icônes et couleurs par matières, personnalisant le skin, etc... mais si je peux le personnaliser, MyDevoirs sera sûrement très pratique pour certains de mes patients, merci.


Merci de m'indiquer ce que vous utiliser pour faire le .exe si possible.

Cordialement
Aurélie PLOTTON

**Comment by jgirardet** [comment]
Bonjour,
Les mises à jours nécessaires sont encore en cours. En pratique, comme je l'ai dit dans #2 , j'aurai plus de temps au début de l'été pour le faire de manière pratique sans fichier de configuration (mon fils rentre aussi en sixième donc ce sera nécessaire). je vous recontacte dès que c fait.

**Comment by berryergo** [comment]
Bonjour,
Merci je suis toujours très interessé par ces modifications. Je cherche toujours toujours quelqu'un pour m'aider à suivre votre démarche.
Bien cordialement
Laure BERRY
 
 
 
 
> Message du 27/04/20 07:43> De : "jgirardet" > A : "jgirardet/mydevoirs" > Copie à : "berryergo" , "Author" > Objet : Re: [jgirardet/mydevoirs] changer les couleurs et les matières (#1)> >
>
> Bonjour,> Les mises à jours nécessaires sont encore en cours. En pratique, comme je l'ai dit dans #2 , j'aurai plus de temps au début de l'été pour le faire de manière pratique sans fichier de configuration (mon fils rentre aussi en sixième donc ce sera nécessaire). je vous recontacte dès que c fait.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/jgirardet/mydevoirs/issues/1#issuecomment-619736151", "url": "https://github.com/jgirardet/mydevoirs/issues/1#issuecomment-619736151", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]


 
What do you want to do ?
New mailCopy

**Comment by jgirardet** [comment]
Bonjour,
Je suis ravi de vous faire par de la sortie d'une nouvelle version de MyDevoirs, qui offre désormais la possibilité d'ajouter/enlever/modifier des matieres via une interface graphique.
Je vous invite à tester avant la rentrer de manière à pouvoir éventuellement faire quelques modifs avant la rentrée si besoin.
Il y a désormais un installeur, ce sera plus simple pour les mises à jour.

Le téléchargement se fait : https://github.com/jgirardet/mydevoirs/releases/download/latest/mydevoirs-1.0.0.msi

Tout est expliqué là https://jgirardet.github.io/mydevoirs/

**Comment by berryergo** [comment]
Bonjour, Un grand merci, je cherchais un informaticien pour me faire ça pour la rentrée.  Je teste et vous tiens au courant.Encore merci pour tous les enfants pour qui vous facilitez le quotidien. Laure berryErgotherapeute Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : jgirardet <notifications@github.com> Date : 23/07/2020  11:09  (GMT+01:00) À : jgirardet/mydevoirs <mydevoirs@noreply.github.com> Cc : berryergo <l.berryergo@orange.fr>, Author <author@noreply.github.com> Objet : Re: [jgirardet/mydevoirs] changer les couleurs et les matières (#1) 

Bonjour,

Je suis ravi de vous faire par de la sortie d'une nouvelle version de MyDevoirs, qui offre désormais la possibilité d'ajouter/enlever/modifier des matieres via une interface graphique.

Je vous invite à tester avant la rentrer de manière à pouvoir éventuellement faire quelques modifs avant la rentrée si besoin.

Il y a désormais un installeur, ce sera plus simple pour les mises à jour.

Le téléchargement se fait : https://github.com/jgirardet/mydevoirs/releases/download/latest/mydevoirs-1.0.0.msi

Tout est expliqué là https://jgirardet.github.io/mydevoirs/
