### ISSUE TITLE
Matière supplémentaires ?

### ISSUE THREAD

**Issue by camillerequis** [jgirardet/mydevoirs#2]
Bonjour je suis ergothérapeute et je trouve votre logiciel vraiment top pour les enfants dys : simple, clair et facile d'utilisation.
Je suis plusieurs enfants pour qui votre logiciel pourrait être super.
Certains sont par contre au collège.. est-il possible de rajouter de matières supplémentaires ? 
Merci et encore bravo pour votre travail !

Camille

**Comment by jgirardet** [comment]
Bonjour,
effectivement c'est un problème que l'on m'a rapporté ici #1 où vous pourrez voir quelques explications à ce sujet. si vous souhaitez vous lancer dans la création d'un fichier de configuration c faisable mais j pense trop compliqué en y réfléchissant.
Quoiqu'il en soit j'ai prévu de rajouter la fonctionnalité à MyDevoirs cet été (pas trop le temps avant). Mon fils rentrera en sixième donc l'évolution sera obligatoire.
Donc je vous propose de de vous refaire signe, dès que c'est ajouté (je pense juillet)

Jimmy

**Comment by camillerequis** [comment]
Bonjour, je vous remercie pour votre réponse. Ok pour cet été c'est super.
Je voulais juste savoir comment a-t-on accès à ce fichier de configuration ? je ne suis pas très callée mais j'aurais bien voulu tenter...
Bonne journée 

Camille

**Comment by jgirardet** [comment]
Je ferme cette discussion au profit de #1  qui est la même question.
