### ISSUE TITLE
synchronisation my devoirs

### ISSUE THREAD

**Issue by pb-ergo** [jgirardet/mydevoirs#21]
Bonjour, 
je suis ergothérapeute en pédiatrie et j'utilise depuis peu votre agenda pour certains des enfants avec lesquels je travaille. 
J'ai besoin qu'il soit synchronisé mais je n'y arrive pas... J'ai fais la manipulation décrite dans l'installation de My devoirs pour le 1er PC.
Mais ensuite, que dois-je faire? à partir du 1er pc synchronisé faut'il que je mette un fichier dans la dropbox? Si oui, lequel?
Et ensuite, que dois-je faire avec l'autre PC? 
(pour info, je ne suis pas informaticienne mais ergothérapeute...!)

Merci d'avance de votre retour et pour la création de cet agenda très simple d'utilisation et bien pratique!
Perrine B.

**Comment by jgirardet** [comment]
Bonjour, désolé de la réponse tardive.
En fait c simplement le principe d'une dropbox : vous ajouter un fichier dans votre dropbox et il sera synchroniser partout où la dropbox sera installé.
Sur le deuxième PC, il fait selectionner le fichier base donnée qui sera synchronisé.
https://www.qwant.com/?q=comprendre%20dropbox&t=videos&o=0:c5585b82add895146e7440ef68fa965b&order=relevance&source=all

**Comment by pb-ergo** [comment]
Pas d souci, merci, je vais essayer alors.
B soirée. Perrine Bernard.

Le mar. 16 févr. 2021 à 20:54, jgirardet <notifications@github.com> a
écrit :
