### ISSUE TITLE
faire commencer la semaine par le DIMANCHE

### ISSUE THREAD

**Issue by LNdys** [jgirardet/mydevoirs#22]
Bonjour, 
Bravo pour la création de Mydevoirs! Mes patients apprécient cet outil!

Seulement mes patients de Bahrein ou Alger ont classe les dimanches et aimeraient avoir la possiblilté de faire paraitre le dimanche comme premier jour de la semaine, pour visualiser la semaine complète. 

Mes patients des USA aussi mais pour des raisons différentes: ils sont habitués à un calendrier qui commence le dimanche!

ESt-ce possible de fgaire ces modifications pour eux? Merci beaucoup

**Comment by jgirardet** [comment]
Je ne vous cache pas mon étonnement en lisant votre message :-)
Je pense que ce n'est pas infaisable, mais il fait que je regarde l'ampleur des changements de nécessaires.
J'essaie de regarder ça cettte semaine.

**Comment by LNdys** [comment]
MERCI bien!

Oui, votre programme est très bien pour nos loulous partout dans le monde!

Hélène Peteau Ergothérapeute
Spécialiste des Troubles des Apprentissages dans les Activités Scolaires
ergotherapie@peteau.com
+34684325047 <+34+684+32+50+47> +33777774528 <+33+7+77+77+45+28>

Marques de Mulhacen 5, 08034, Barcelona
<http://maps.apple.com/?q=Marques+de+Mulhacen+5,08034,Barcelona>

[image: Facebook]
<https://facebook.com/https://www.facebook.com/HelenePeteauBCN/> [image:
Instagram] <https://instagram.com/ergopedagogie.barcelona> [image: WhatsApp]
<https://wa.me/https://wa.link/9eko9t>

Nota:

Este mensaje es confidencial y va dirigido al destinatario de este correo.
Si lo ha recibido por error, le rogamos que informe al emisor del mismo y
lo borre de su sistema. Cualquier persona distinta de su destinatario no
está autorizada a reenviarlo, leerlo, imprimirlo o a hacer uso de su
contenido. Hélène Peteau Terapeuta Ocupacional



Le lun. 15 févr. 2021 à 16:11, jgirardet <notifications@github.com> a
écrit :

**Comment by jgirardet** [comment]
ça a l'air bon, il faut télécharger la nouvelle version.
Il faut choisir le premier jour de la semaine dans les options et désactiver "afficher la semaine suivante" (qui suppose que le WE est toujours le samedi dimanche)
