### ISSUE TITLE
Disponibilité sur Mac

### ISSUE THREAD

**Issue by NATMA07** [jgirardet/mydevoirs#24]
Bonjour,

Mon fils a besoin d'un agenda pour l'école. On m'a recommandé votre logiciel. Est-ce possible de le télécharger sur MAC ? Il parait que c'est possible sur demande, mais je ne vois pas où de sorte que je vous écris ici.
Pouvez vous me dire comment accéder à votre logiciel Mydevoirs ? Mon fils a un Mac book air et moi un Mac book pro.

Bien cordialement,

Marianne

**Comment by jgirardet** [comment]
Bonjour
JE n'ai pas la  possibilité de développement sur mac Je ne peux donc pas le proposer sur le moment.
JE vais changer la documentation.
