### ISSUE TITLE
Taille des cases

### ISSUE THREAD

**Issue by heleneergo** [jgirardet/mydevoirs#26]
Bonjour,
La taille des cases journée de l'agenda est-elle limitée ?
Un collégien n'a pas pu écrire tous ses devoirs car il n'y avait plus de place.
Hélène Ergothérapeute

**Comment by jgirardet** [comment]
Bonjour,
Oui, la taille est limitée, c volontaire.
L'idée est de limiter le contenu par ligne afin de mieux forcer à séparer chaque tâche. Il peut faire controler `Ctrl + D` pour ajouter rapidement une nouvelle ligne de la même matiere.
