### ISSUE TITLE
My devoir pour Mac

### ISSUE THREAD

**Issue by Eline2008** [jgirardet/mydevoirs#27]
Bonjour, 
Serait il possible d'avoir un lien pour le téléchargement de My devoir pour Mac. Ce logiciel nous a été conseiller par l'ergo de ma fille qui en aurait besoin pour la rentrée.
Merci d'avance
Bien cordialement
TONERIE baptiste

**Comment by jgirardet** [comment]
Bonjour,
Il n'existe pas de version Mac pour Mydevoirs, je suis désolé.
cordialement

**Comment by Eline2008** [comment]
Bonjour, il me semblait avoir lu que la version pour Mac était disponible sur demande ?
Tenez moi  au courant 
Bien cordialement
Baptiste

**Comment by jgirardet** [comment]
Il n'existe pas de version Mac actuellement
