### ISSUE TITLE
Personnalisation MyDevoirs

### ISSUE THREAD

**Issue by Lizexx** [jgirardet/mydevoirs#28]
Bonjour,
Depuis quelques temps, l'outil "palette" permettant de modifier le nom des matières et de personnaliser les couleurs n'apparaît plus sur l'ordinateur. C'est bien dommage car il m'était indispensable. Comment faire pour accéder de nouveau à ces fonctions ?

Merci pour votre aide et votre super travail !

**Comment by jgirardet** [comment]
Ici il s'affiche toujours.
est ce bien la dernière version que vous utilisez ?
