### ISSUE TITLE
MyDevoirs qui se ferme

### ISSUE THREAD

**Issue by michelexx** [jgirardet/mydevoirs#30]
Bonjour,
MyDevoirs se ferme dès que l'on clic sur les paramètres, sur la palette, sur les flèches pour changer de semaine ou pour ajouter des matières dans les cases des jours.
J'ai désinstallé et réinstallé, mais cela ne change rien

Merci pour votre retour

**Comment by jgirardet** [comment]
dans le répertoire : `c:\Users\<nomdelutilisateur>\AppData\Local\Mydevoirs` vous trouverez un fichier settings.
Pouvez vous me montrer le contenu de ce fichiers ?
le fichier à côté `.sqlite` est la base de donnée (si vous ne l'avez pas déplacée ailleurs), faites en une sauvegarde.
Ensuite vous pouvez essayer de supprimer complètement le répertoire et relancer MyDevoirs.
Utilisez bien la dernière version (1.1.0)
