### ISSUE TITLE
L'application ne s'ouvre plus

### ISSUE THREAD

**Issue by gaeljoret** [jgirardet/mydevoirs#31]
Bonjour,
Je n'arrive plus à ouvrir l'application. Je l'ai désinstallés et réinstallée. Je suis sous Windows 11. Malheureusement rien ne change. Lorsque je clique sur l'icône, une fenêtre blanche de démarrage de l'application s'ouvre puis se ferme immédiatement.
Pourriez-vous m'aider s'il vous plait?
Cordialement

**Comment by jgirardet** [comment]
dans le répertoire : `c:\Users\<nomdelutilisateur>\AppData\Local\Mydevoirs` vous trouverez un fichier settings.
Pouvez vous me montrer le contenu de ce fichiers ?
le fichier à côté `.sqlite` est la base de donnée (si vous ne l'avez pas déplacée ailleurs), faites en une sauvegarde.
Ensuite vous pouvez essayer de supprimer complètement le répertoire et relancer MyDevoirs.
Utilisez bien la dernière version (1.1.0)

**Comment by gaeljoret** [comment]
Un grand merci pour votre retour très rapide. Voici une capture d’écran du contenu demandé :

 



 

J’ai déjà réinstallé 3 fois en utilisant, il me semble, la dernière version. J’ai dû effectivement faire quelque chose en cherchant dans les paramètres du programme (je voulais créé des nouvelles matières) mais je ne sais vraiment pas ce que j’ai fait.

 

Merci de l’aide que vous voulez bien m’apporter

 

De : jgirardet ***@***.***> 
Envoyé : dimanche 1 mai 2022 10:26
À : jgirardet/mydevoirs ***@***.***>
Cc : gaeljoret ***@***.***>; Author ***@***.***>
Objet : Re: [jgirardet/mydevoirs] L'application ne s'ouvre plus (Issue #31)

 

dans le répertoire : c:\Users\<nomdelutilisateur>\AppData\Local\Mydevoirs vous trouverez un fichier settings.
Pouvez vous me montrer le contenu de ce fichiers ?
le fichier à côté .sqlite est la base de donnée (si vous ne l'avez pas déplacée ailleurs), faites en une sauvegarde.
Ensuite vous pouvez essayer de supprimer complètement le répertoire et relancer MyDevoirs.
Utilisez bien la dernière version (1.1.0)

**Comment by jgirardet** [comment]
Pas d'image visible.
sinon un copier coller du contenu

**Comment by gaeljoret** [comment]
Mes excuses. Voici les 2 fichiers joints contenus dans le dossier du chemin évoqué

 

De : jgirardet ***@***.***> 
Envoyé : dimanche 1 mai 2022 11:41
À : jgirardet/mydevoirs ***@***.***>
Cc : gaeljoret ***@***.***>; Author ***@***.***>
Objet : Re: [jgirardet/mydevoirs] L'application ne s'ouvre plus (Issue #31)

 

Pas d'image visible.
sinon un copier coller du contenu
