### ISSUE TITLE
Ajout d'une fonctionnalité pour changer le jour d'un devoir

### ISSUE THREAD

**Issue by Chouquette33** [jgirardet/mydevoirs#32]
Bonjour, il arrive à ma fille de se tromper de jour lors de la saisie d'un devoir sauf erreur de ma part il est nécessaire de recréer le devoir sur le bon jour et de supprimer l'autre. Alors je me dis qu'une petite fonctionnalité pour déplacer le devoir vers le bon jour ou modifier la date sans devoir tout ressaisir serait top ! Et ferait moins râler la maîtresse !
Merci d'avance.

**Comment by jgirardet** [comment]
désolé pour la réponse tardive.  Peu de temps en ce moment.
j'essaie de faire une mise à jour dans l'été
