### ISSUE TITLE
Demande d'autorisation

### ISSUE THREAD

**Issue by NOELDIAMANTBERGER** [jgirardet/mydevoirs#33]
Bonjour,
Je m'appelle Noël DIAMANT-BERGER et président l'association FUSO FRANCE qui équipe, forme et accompagnent, depuis 2014, des enfants équipés d'un cartable numérique que nous leur proposons : un environnement logiciel adapté sur une base windows / OneNote / Studys /PDF exchange Editor, entre autre. Nous envoyons les ordinateurs paramétrés par la poste et formons les enfants en distantiels, dans toute la France et au-delà, sans subvention ni salariés (seuls les formateurs, des parents devenus experts en bureautique) sont rémunérés pour les cours qu'ils donnent. 
Notre équipe, qui a découvert votre formidable outil, voudrait vous demander l'autorisation de l'installer sur nos cartables numériques. J'aimerai aussi vous remercier infiniment pour ce travail, entrer en contact avec vous, nous présenter mutuellement et, qui sait, collaborer car vous êtes de ceux qui, comme nous, ne manquez pas d'idées pour faciliter la vie de nos enfants. 
Solidairement,

Noël DIAMANT-BERGER 06 08 55 49 73 noel@fusofrance.org

**Comment by jgirardet** [comment]
Bonjour,
Merci pour ce sympathique commentaire.
La licence vous permet de l'utiliser comme vous le souhaitez et sans permission préalable de ma part.
Je pensais faire probablement une nouvelle version cet été (rien de décidé pour le moment, quelques amélioration...)
Cordialement
