### ISSUE TITLE
Problème : Mydevoirs ne s'ouvre plus

### ISSUE THREAD

**Issue by AL-RENAUD** [jgirardet/mydevoirs#35]
Bonsoir,
L'ergothérapeute de mon fils lui a installé Mydevoirs l'année scolaire dernière. Ce logiciel est top! Merci!
Malheureusement, nous avons voulu l'utiliser à nouveau dès le premier jour d'école la semaine dernière et il ne s'ouvre plus. Il est bien installé dans l'ordinateur mais rien à faire. Nous l'avons désinstallé - réinstallé et ça ne change rien.
Pourriez-vous nous aider svp ?
Merci beaucoup,
AL Renaud

**Comment by jgirardet** [comment]
dans le répertoire : c:\Users\<nomdelutilisateur>\AppData\Local\Mydevoirs vous trouverez un fichier settings.
Pouvez vous me montrer le contenu de ce fichiers ?
le fichier à côté .sqlite est la base de donnée (si vous ne l'avez pas déplacée ailleurs), faites en une sauvegarde.
Ensuite vous pouvez essayer de supprimer complètement le répertoire et relancer MyDevoirs.
Utilisez bien la dernière version (1.1.0)

**Comment by AL-RENAUD** [comment]
Merci, nous avons fait votre manip et bidouiller un peu (car il s'ouvrait parfaitement sur la session Admin mais pas sur la session de mon fils) et ça fonctionne ! Merci pour votre aide
