### ISSUE TITLE
Contrastes agenda

### ISSUE THREAD

**Issue by Mathildeija** [jgirardet/mydevoirs#36]
Bonjour,
Je suis ergothérapeute et je travaille dans un sessad avec des enfants qui ont une déficience visuelle. Je viens de découvrir votre agenda "mydevoirs" qui est très intéressant. 
Y'a t il une possibilité d'avoir un contraste plus important sur l'affichage de l'agenda (affichage des jours) ? (exemple fond noir écriture blanche)
Merci par avance
Mathilde

**Comment by jgirardet** [comment]
Bonjour,
uniquement pour les jours ?

**Comment by Mathildeija** [comment]
Bonjour,
Oui essentiellement dans les cases des jours (où les couleurs sont plutôt grises). Avec un enfant en particulier qui a besoin d'un fort contraste et d'une police un peu plus grosse, l'idéal serait fond noir écriture blanche... et pourquoi pas une police un peu plus grande 
merci par avance

**Comment by jgirardet** [comment]
une nouvelle version est disponible.
Il faut aller dans les options et choisir theme->contrast (et redémarrer mydevoirs si besoin)
merci de me tenir au courant.

**Comment by Mathildeija** [comment]
Merci beaucoup, pour l'option contraste c'est parfait
