### ISSUE TITLE
ouverture automatique de Mydevoirs

### ISSUE THREAD

**Issue by LaurenceMathias** [jgirardet/mydevoirs#44]
Bonjour, 
je viens de découvrir Mydevoirs et je le trouve très intuitif et visuel pour mes petits patients. 
Est-il possible de paramétrer une ouverture automatique du logiciel à l'allumage de l'ordinateur, de sorte que l'agenda soit automatiquement visible en fond d'écran ? 
Merci d'avance. 
Laurence

**Comment by jgirardet** [comment]
c n'est pas mydevoirs qui est responsable de cela mais windows.
voici la marche à suivre : https://support.microsoft.com/fr-fr/windows/ajouter-une-application-pour-qu-elle-s-ex%C3%A9cute-automatiquement-au-d%C3%A9marrage-dans-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

**Comment by LaurenceMathias** [comment]
Ca fonctionne ! Merci beaucoup ! 👍🏻

Le ven. 15 sept. 2023 à 11:01, jgirardet ***@***.***> a
écrit :
