### ISSUE TITLE
déficience visuelle

### ISSUE THREAD

**Issue by rozennErgo** [jgirardet/mydevoirs#46]
Bonjour,

Ergothérapeute, J'accompagne des élèves déficients visuels pour leur autonomie scolaire. Je trouve votre logiciel très bien fait pour leur organisation, hélas trop petit à l'écran pour leurs besoins de grossissement. Serait-il possible de réfléchir ensemble à une solution ? (en général, les plus déficients visuels sont sur un police Luciole ou Arial Black 26.)

Merci par avance pour votre réponse! 

Cordialement, 

Rozenn RENAULT
rozenn.savsdv@gmail.com

**Comment by jgirardet** [comment]
Bonjour,
Je n'ai malheureusement plus le temps de maintenir MyDevoirs à jours et d'assurer une aide adéquate.
Merci pour l’intérêt que vous avec porté à MyDevoirs etj'aurai vraiment voulu pouvoir faire quelque chose.
Merci pour votre compréhension et bon courrage
