### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by GaelleErgo** [jgirardet/mydevoirs#47]
Bonjour,

A l'installation du logiciel sur le PC d'un enfant que j'accompagne deux codes erreurs apparaissent : 2503 et 2502. 
Je n'ai jamais eu ce problème auparavant. Que dois-je faire? 

Merci d'avance

**Comment by jgirardet** [comment]
Bonjour,
Je n'ai malheureusement plus le temps de maintenir MyDevoirs à jours et d'assurer une aide adéquate.
Peut-être essayer de tout désinstaller ?
Merci pour votre compréhension.
